### ISSUE TITLE
Добавить правило на использование debug от testing-library

### ISSUE THREAD

**Issue by korniux** [sima-land/frontend-linters#30]
Проблема: пропускается `debug()` функция от `testing-library` под гит в следствии которой логи CI становятся менее читаемыми. 

Задача: добавить правило для ESLint `"testing-library/no-debugging-utils": "error"` из пакета https://github.com/testing-library/eslint-plugin-testing-library

**Comment by krutoo** [comment]
https://github.com/testing-library/eslint-plugin-testing-library

тут чето про дебаг есть, не подощло?
